use mysql;
create database XXXXDB_NXXXX;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,LOCK TABLES,INDEX ON XXXXDB_NXXXX.* TO 'XXXXDB_UXXXX'@'%' WITH GRANT OPTION;
GRANT SHOW DATABASES ON *.* TO 'XXXXDB_UXXXX'@'%';
flush privileges;
