CREATE USER XXXXDB_UXXXX@'localhost' IDENTIFIED WITH caching_sha2_password BY 'XXXXDB_PXXXX';
CREATE USER XXXXDB_UXXXX@'127.0.0.1' IDENTIFIED WITH caching_sha2_password BY 'XXXXDB_PXXXX';
CREATE USER XXXXDB_UXXXX@'XXXXIP_MASKXXXX' IDENTIFIED WITH caching_sha2_password BY 'XXXXDB_PXXXX';
