use mysql;
CREATE USER XXXXDB_UXXXX IDENTIFIED BY 'XXXXDB_PXXXX';
flush privileges;
create database XXXXDB_NXXXX;
ALTER DATABASE XXXXDB_NXXXX CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,INDEX ON XXXXDB_NXXXX.* TO 'XXXXDB_UXXXX'@'localhost' IDENTIFIED BY 'XXXXDB_PXXXX' WITH GRANT OPTION;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,INDEX ON XXXXDB_NXXXX.* TO 'XXXXDB_UXXXX'@'127.0.0.1' IDENTIFIED BY 'XXXXDB_PXXXX' WITH GRANT OPTION;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,INDEX ON XXXXDB_NXXXX.* TO 'XXXXDB_UXXXX'@'XXXXIP_MASKXXXX' IDENTIFIED BY 'XXXXDB_PXXXX' WITH GRANT OPTION;
drop user root@localhost;
drop user mysql@localhost;
flush privileges;

