use mysql;
create database XXXXDB_NXXXX;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,LOCK TABLES,SHOW DATABASES,INDEX ON XXXXDB_NXXXX.* TO 'XXXXDB_UXXXX'@'%' WITH GRANT OPTION;
flush privileges;
