SET sql_require_primary_key=0;
use mysql;
CREATE USER 'XXXXDB_UXXXX'@'XXXXHOSTXXXX' IDENTIFIED BY 'XXXXDB_PXXXX';
flush privileges;
create database XXXXDB_NXXXX;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,LOCK TABLES,INDEX ON XXXXDB_NXXXX.* TO 'XXXXDB_UXXXX'@'XXXXHOSTXXXX' WITH GRANT OPTION;
flush privileges;
